INDIAN_CLAUSE_TYPES = {
    "SHA_ROFR": {
        "label": "Right of First Refusal (SHA)",
        "risk": "high",
        "preferred": "Pre-emptive rights on any transfer of shares at fair market value with a 30-45 day exercise period. Transferor must serve ROFR notice to all existing shareholders. Non-exercising shareholders deemed to have waived rights.",
        "if_missing": "Missing ROFR allows shareholders to transfer shares to third parties without giving existing holders a first right to purchase — may violate Section 56 of Companies Act 2013 for private company share transfers",
        "if_deviates": "Exercise period below 15 days may be challenged as unreasonable. No FMV mechanism may lead to disputes under the Companies Act valuation rules",
        "required": True,
    },
    "SHA_TagAlong": {
        "label": "Tag-Along Rights (SHA)",
        "risk": "high",
        "preferred": "Tag-along rights for ALL minority shareholders on any sale by majority holders at same price and terms. Trigger at 1% or more share transfer.",
        "if_missing": "Minority shareholders cannot exit on same terms as majority in a sale — SEBI SAST Regulations provide this for listed cos but not private cos",
        "if_deviates": "Tag threshold above 5% leaves small minority unprotected. Restricted to certain classes discriminates against other shareholders",
        "required": True,
    },
    "SHA_DragAlong": {
        "label": "Drag-Along Rights (SHA)",
        "risk": "high",
        "preferred": "Drag-along by holders of 75%+ shares; minority to receive same price and consideration as majority; bona fide third-party acquirer.",
        "if_missing": "Blocking minority can prevent a full exit/sale — problematic in VC/PE exits under Indian M&A practice",
        "if_deviates": "Threshold below 66% may be oppressive to minority. Drag-along to founders at below-market price may be challenged as unconscionable under Indian Contract Act Section 16",
        "required": False,
    },
    "SHA_AntiDilution": {
        "label": "Anti-Dilution (SHA)",
        "risk": "high",
        "preferred": "Weighted average anti-dilution protection for preference shareholders. Full ratchet rarely accepted in Indian market.",
        "if_missing": "No protection against future down-rounds diluting existing investors — significant risk for PE/VC investors",
        "if_deviates": "Full ratchet anti-dilution is highly aggressive and rarely accepted in Indian venture deals. Pay-to-play provisions may force conversion",
        "required": False,
    },
    "SHA_BoardComposition": {
        "label": "Board Composition (SHA)",
        "risk": "medium",
        "preferred": "Board proportional to shareholding; investor right to appoint one director if holding >10%; at least 1 woman director (per Companies Act 2013 Section 149).",
        "if_missing": "No board representation rights for minority investors — may violate corporate governance norms under Companies Act Schedule IV",
        "if_deviates": "Founder-controlled board with no investor representation limits minority protection. May not comply with Section 149(1) woman director requirement",
        "required": True,
    },
    "SHA_Quorum": {
        "label": "Quorum & Meeting (SHA)",
        "risk": "medium",
        "preferred": "Quorum of 2 members present in person; certain matters (amendment of SHA, change in share capital, M&A) require 75%+ affirmative vote of total shareholders.",
        "if_missing": "Company can pass resolutions without adequate minority participation — may violate Section 103 of Companies Act 2013",
        "if_deviates": "Unusually high quorum requirements (>90%) can cause operational deadlock. Matters not listed as special may bypass minority protection",
        "required": False,
    },
    "SHA_Liquidation": {
        "label": "Liquidation Preference (SHA)",
        "risk": "high",
        "preferred": "Seniority-based liquidation preference, non-participating preferred, capped at original investment amount plus accrued dividends.",
        "if_missing": "No clarity on distribution waterfall upon winding up — may conflict with Section 325 of Companies Act 2013 (preferential payments)",
        "if_deviates": "Participating preference with uncapped upside is unfavourable to founders and uncommon in India post-2019. Multiple liquidation preference stacks are rare",
        "required": False,
    },
    "JVA_ManagementCommittee": {
        "label": "Management Committee (JVA)",
        "risk": "medium",
        "preferred": "MC with equal representation from both JV partners; chairman from largest shareholder with casting vote only in deadlock.",
        "if_missing": "No governance structure for operational decisions — leads to deadlock in JV operations under the Companies Act board structure",
        "if_deviates": "Unequal representation may disadvantage minority JV partner. Chairman with full casting vote may give disproportionate control",
        "required": True,
    },
    "JVA_Deadlock": {
        "label": "Deadlock Resolution (JVA)",
        "risk": "high",
        "preferred": "Escalation to CEO/Board, then mediation under Indian Arbitration Act, then buy-out clause (Russian roulette or Texas shoot-out). Failing resolution, winding up under Section 271 of Companies Act 2013.",
        "if_missing": "Deadlock can freeze JV operations with no exit mechanism — most common cause of JV failure in India",
        "if_deviates": "Only buy-out with no mediation may trigger unnecessary litigation. Without buy-out mechanism, parties may need NCLT winding up",
        "required": True,
    },
    "Dispute_ArbitrationSeat": {
        "label": "Arbitration Seat (India)",
        "risk": "high",
        "preferred": "Seat at Mumbai/Delhi/Bengaluru; arbitration under Arbitration and Conciliation Act 1996; SIAC, ICC, or ICA rules; 3 arbitrators for high-value, 1 for others.",
        "if_missing": "No seat/clause allows parties to choose after dispute arises, causing delay. Without arbitration, courts have exclusive jurisdiction under CPC",
        "if_deviates": "Seat outside India (Singapore/London) increases cost for Indian party significantly (10-20x). Foreign award enforcement under Part II of Arbitration Act more complex (public policy challenge under Section 34)",
        "required": True,
    },
    "DataProtection_DPDP": {
        "label": "Data Protection (DPDP Act 2023)",
        "risk": "high",
        "preferred": "Full compliance with Digital Personal Data Protection Act 2023; data localization for sensitive data; consent mechanism per Section 6; DPO appointment if Significant Data Fiduciary.",
        "if_missing": "Exposure to penalties under DPDP Act 2023 (up to INR 250 crores under Section 34-36). Non-compliance with CERT-In 6-hour breach reporting",
        "if_deviates": "Weaker data protection than DPDP Act minimum violates Indian law. Cross-border transfer without adequacy notification violates Section 33",
        "required": True,
    },
    "Employment_NoticePeriod": {
        "label": "Notice Period (Employment)",
        "risk": "medium",
        "preferred": "90 days by senior employee; 60 days by employer; garden leave at employer's discretion during notice period.",
        "if_missing": "No notice period makes termination unpredictable. May conflict with standing orders under Industrial Employment Act or state-specific S&E Acts",
        "if_deviates": "Notice below 30 days may violate minimum standards under state Shops and Establishments Acts. Instant termination without cause is challenged under Industrial Disputes Act",
        "required": True,
    },
    "Employment_RestrictiveCovenant": {
        "label": "Restrictive Covenant (Employment)",
        "risk": "high",
        "preferred": "Non-solicit of clients/employees for 6 months post-termination; confidentiality during and after employment. NO non-compete clause in employment (void under Section 27, Indian Contract Act 1872).",
        "if_missing": "Key employees can immediately solicit clients and team — significant business risk",
        "if_deviates": "Non-compete clause in employment contract is VOID under Section 27 of Indian Contract Act 1872 (Niranjan Shankar Golikari v. Century Spinning, AIR 1967 SC 1098). Only enforceable if part of sale of goodwill or if employee receives consideration. Non-solicit must be reasonable in scope, geography, and duration",
        "required": False,
    },
    "IP_Assignment": {
        "label": "IP Assignment (India)",
        "risk": "high",
        "preferred": "Present and future IP assigned with worldwide rights; moral rights waived where permitted by Indian Copyright Act 1957; employee works made-for-hire provisions.",
        "if_missing": "IP ownership remains with creator, not the company — employer must obtain separate assignment under Indian Copyright Act Section 17",
        "if_deviates": "Limited territorial scope or failure to address moral rights (Section 57, Indian Copyright Act — moral rights are inalienable). No future IP assignment creates gap",
        "required": True,
    },
    "Tax_Withholding": {
        "label": "Tax Withholding (India)",
        "risk": "medium",
        "preferred": "Gross-up for Indian taxes; TDS deducted per Income Tax Act 1961 Sections 194C/194J; withholding tax certificates provided within 30 days; PAN requirements per Section 206AA.",
        "if_missing": "Non-compliance with TDS provisions leads to disallowance under Section 40(a)(ia) — expense disallowed at 30%. Interest under Section 201",
        "if_deviates": "No gross-up places entire tax burden on recipient. Non-PAN deduction at 20% u/s 206AA. Failure to provide TDS certificates may breach recipient's compliance",
        "required": False,
    },
    "Tax_Indemnity": {
        "label": "Tax Indemnity (M&A)",
        "risk": "high",
        "preferred": "Seller indemnifies for pre-closing tax liabilities; survival 7 years (Section 149 of Income Tax Act — 6-year assessment window for significant tax issues); no cap on fraud/tax matters.",
        "if_missing": "Buyer assumes all historical tax risk — Indian tax department has 6-year assessment window (Section 149, Income Tax Act 1961), 16 years for assets outside India",
        "if_deviates": "Survival less than 6 years is insufficient given Indian tax assessment timelines. Cap on tax indemnity leaves buyer exposed to reassessment under Section 147-148",
        "required": True,
    },
    "GST_Compliance": {
        "label": "GST Compliance (India)",
        "risk": "medium",
        "preferred": "GST payable as applicable under CGST/SGST/IGST Acts 2017; both parties to have valid GST registration; input tax credit eligibility confirmed; e-invoicing if applicable.",
        "if_missing": "Non-compliance exposes parties to GST penalties under Section 122 of CGST Act (10% of tax or INR 10K, whichever higher). Interest under Section 50",
        "if_deviates": "Contract silent on GST applicability may lead to disputes on tax liability. RCM (Reverse Charge Mechanism) obligations must be clearly allocated. E-invoicing threshold compliance (turnover > INR 5Cr)",
        "required": False,
    },
    "Indemnification_Indian": {
        "label": "Indemnification (India)",
        "risk": "high",
        "preferred": "Full indemnity for breach, IP infringement, third-party claims; cap at 100% of contract value; survival 6 years (Limitation Act 1963); notice within 30 days of claim.",
        "if_missing": "No remedy for losses caused by breach — Indian Contract Act Sections 124-125 provide limited implied indemnity. Third-party IP claims could be unlimited",
        "if_deviates": "Cap below 100% inadequate for most Indian commercial contracts. Survival less than 3 years risks running into Limitation Act 1963 bar. Excluding fraud from cap is mandatory per Indian public policy",
        "required": True,
    },
    "Liability_Cap_Indian": {
        "label": "Limitation of Liability (India)",
        "risk": "high",
        "preferred": "Liability cap at 100% of contract value; excludes fraud, gross negligence, IP infringement, breach of confidentiality, death/injury, statutory penalties. Several liability for multi-party contracts.",
        "if_missing": "Unlimited liability exposure. No cap is rare in Indian commercial contracts",
        "if_deviates": "Cap below 50% insufficient for most Indian commercial contracts. Must exclude fraud (public policy exception under Indian Contract Act). Consequential damages exclusion standard but must be unambiguous",
        "required": True,
    },
    "ForceMajeure_Indian": {
        "label": "Force Majeure (India)",
        "risk": "low",
        "preferred": "Standard FM covering acts of God, pandemic, war, government action, strikes; notice within 7 days; mitigation obligation; termination right if >90 days; Section 56 of Indian Contract Act applies as residual.",
        "if_missing": "Without FM clause, force majeure is governed by Section 56 of Indian Contract Act (Doctrine of Frustration) — narrower than typical FM clause. Frustration must make performance impossible, not just difficult (Satyabrata Ghose v. Mugneeram Bangur, AIR 1954 SC 44)",
        "if_deviates": "No pandemic clause risks ambiguity (post-COVID Indian courts expect explicit pandemic coverage). Termination only after FM period consistent with Indian law. Section 56 requires impossibility, not impracticability",
        "required": False,
    },
    "GoverningLaw_Indian": {
        "label": "Governing Law (India)",
        "risk": "high",
        "preferred": "Governing law of India; courts at [Mumbai/Delhi/Bengaluru] have exclusive jurisdiction. Limitation governed by Limitation Act 1963.",
        "if_missing": "Uncertain which law governs the contract — may lead to conflict of laws issues under Indian conflict rules",
        "if_deviates": "Foreign governing law may be unenforceable for Indian immovable property under Section 2(b) of Indian Contract Act. Indian courts may refuse to apply foreign law if contrary to public policy. Exclusive foreign jurisdiction clauses must be clear and unequivocal (MOD Entertainment v. Kiev Court, 2023 SCC OnLine SC 931)",
        "required": True,
    },
    "Warranty_Indian": {
        "label": "Warranty & Disclaimer (India)",
        "risk": "medium",
        "preferred": "Mutual warranties for authority, no breach of law, no litigation. Disclaimer of implied warranties subject to Sale of Goods Act 1930 (Section 55-57 allows exclusion but reasonableness test may apply).",
        "if_missing": "No statutory warranties under Indian law for service contracts (unlike Sale of Goods Act for goods). Implied warranties under Sale of Goods Act 1930 Sections 14-17 apply to goods only",
        "if_deviates": "Complete disclaimer of ALL warranties may be unconscionable under Indian Contract Act. Disclaimer of title/quiet possession may be void as against public policy",
        "required": False,
    },
    "Termination_Indian": {
        "label": "Termination (India)",
        "risk": "medium",
        "preferred": "Termination for convenience (30 days notice for services); termination for cause (material breach with 30 day cure period); termination for insolvency; survival of confidentiality, IP, and indemnity.",
        "if_missing": "Without termination clause, Section 62-67 of Indian Contract Act apply — may not align with commercial intentions. Courts may imply reasonable notice per common law",
        "if_deviates": "Termination without cure period may be challenged. For cause must be clearly defined (material breach, insolvency, change of control). Survival clauses must explicitly list surviving provisions",
        "required": False,
    },
}


def get_indian_presets() -> dict:
    return INDIAN_CLAUSE_TYPES
